name: BAS-BanksUtility
env:
  PUBLISH_DIR: bin/Release/net6.0/publish/wwwroot

# Controls when the action will run
on:
  push:
    branches: [ master ]
    paths:
      - 'BASBanksUtility.csproj'
permissions:
    contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: ls
      run : ls -l -R
      
    # changes the base-tag in index.html from '/' to 'BlazorGitHubPagesDemo' to match GitHub Pages repository subdirectory
    - name: Change base-tag in index.html from / to BASBanksUtility
      run: sed -i 's/<base href="\/" \/>/<base href="\/BASBanksUtility\/" \/>/g' wwwroot/index.html

    - name: Publish app
      run: dotnet publish -c Release
      
    - name: GitHub Pages
      if: success()
      uses: crazy-max/ghaction-github-pages@v4
      with:
        target_branch: gh-pages
        build_dir: ${{ env.PUBLISH_DIR }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        FOLDER: ${{ env.PUBLISH_DIR }}
